// ─────────────────────────────────────────────────────────────
// routes/teacher-ai/index.js
//
// Teacher AI (Teaching Assistant) module — Part 1 of the Sabino Edu
// addendum v1.1. Mounted in index.js at /api/teacher-ai.
//
// Sub-routes:
//   /api/teacher-ai/chat              — the "Ask Sabino AI" chat (chat.js)
//   /api/teacher-ai/scheme-of-work    — Scheme of Work documents
//   /api/teacher-ai/lesson-plans      — Lesson Plan documents
//   /api/teacher-ai/lesson-notes      — Lesson Note documents
//
// The three document endpoints are all generated by the same factory
// (documents.js) since, per the addendum, they share one identical
// generation-and-review pattern.
// ─────────────────────────────────────────────────────────────
const express = require('express');
const router = express.Router();

const chatRouter = require('./chat');
const { buildDocumentsRouter } = require('./documents');

router.use('/chat', chatRouter);
router.use('/scheme-of-work', buildDocumentsRouter('scheme-of-work'));
router.use('/lesson-plans', buildDocumentsRouter('lesson-plans'));
router.use('/lesson-notes', buildDocumentsRouter('lesson-notes'));

module.exports = router;
