#!/usr/bin/env node

/**
 * database/backup-db.js
 *
 * Full-fidelity PostgreSQL backup using pg library (no pg_dump dependency).
 * Captures: sequences, tables (with all constraints), indexes, data.
 * Compresses with gzip and emails the result.
 *
 * Triggered by cron in index.js (daily at 12:00 AM UTC).
 */

const { Client } = require('pg');
const { createGzip } = require('zlib');
const nodemailer = require('nodemailer');
const path = require('path');

require('dotenv').config({ path: path.resolve(__dirname, '../.env.local') });

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

function log(msg) {
  console.log(`[${new Date().toISOString()}] [DB-BACKUP] ${msg}`);
}

function getTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

/**
 * Safely escape a value for insertion into a SQL VALUES clause.
 * Handles: null, booleans, numbers, dates, objects (JSONB), strings.
 */
function escapeValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') return value.toString();
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (typeof value === 'object') {
    // JSONB / arrays
    return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  }
  // Strings — escape single quotes
  return `'${String(value).replace(/'/g, "''")}'`;
}

// ─────────────────────────────────────────────
// CORE DUMP
// ─────────────────────────────────────────────

async function dumpDatabase() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();
  log('Connected to database');

  let dump = '';
  dump += `-- ============================================================\n`;
  dump += `-- Full database backup: ${new Date().toISOString()}\n`;
  dump += `-- Generated by backup-db.js (pg library)\n`;
  dump += `-- ============================================================\n\n`;
  dump += `SET client_encoding = 'UTF8';\n`;
  dump += `SET standard_conforming_strings = on;\n\n`;

  // ── 1. SEQUENCES ──────────────────────────────────────────────────
  dump += await dumpSequences(client);

  // ── 2. TABLES (structure + data) ─────────────────────────────────
  // Fetch tables in dependency order (parents before children)
  const tablesResult = await client.query(`
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename
  `);
  const tables = tablesResult.rows.map(r => r.tablename);
  log(`Found ${tables.length} tables: ${tables.join(', ')}`);

  for (const table of tables) {
    log(`Dumping table: ${table}`);
    dump += await dumpTable(client, table);
  }

  // ── 3. INDEXES ────────────────────────────────────────────────────
  dump += await dumpIndexes(client);

  // ── 4. RESET SEQUENCES to match current data ─────────────────────
  dump += await dumpSequenceResets(client, tables);

  await client.end();
  log('Database dump completed');
  return dump;
}

// ─────────────────────────────────────────────
// SEQUENCES
// ─────────────────────────────────────────────

async function dumpSequences(client) {
  const result = await client.query(`
    SELECT sequence_name, start_value, minimum_value, maximum_value,
           increment, cycle_option
    FROM information_schema.sequences
    WHERE sequence_schema = 'public'
    ORDER BY sequence_name
  `);

  if (result.rows.length === 0) return '';

  let out = `-- ── Sequences ──────────────────────────────────────────────────\n\n`;
  for (const seq of result.rows) {
    const cycle = seq.cycle_option === 'YES' ? 'CYCLE' : 'NO CYCLE';
    out += `CREATE SEQUENCE IF NOT EXISTS "${seq.sequence_name}"\n`;
    out += `  START WITH ${seq.start_value}\n`;
    out += `  INCREMENT BY ${seq.increment}\n`;
    out += `  MINVALUE ${seq.minimum_value}\n`;
    out += `  MAXVALUE ${seq.maximum_value}\n`;
    out += `  ${cycle};\n\n`;
  }
  return out;
}

// ─────────────────────────────────────────────
// TABLE STRUCTURE + DATA
// ─────────────────────────────────────────────

async function dumpTable(client, table) {
  let out = `-- ── Table: ${table} ─────────────────────────────────────────────\n\n`;
  out += `DROP TABLE IF EXISTS "${table}" CASCADE;\n`;
  out += `CREATE TABLE "${table}" (\n`;

  // Columns
  const colsResult = await client.query(`
    SELECT
      c.column_name,
      c.data_type,
      c.udt_name,
      c.character_maximum_length,
      c.numeric_precision,
      c.numeric_scale,
      c.is_nullable,
      c.column_default,
      c.is_generated,
      c.generation_expression
    FROM information_schema.columns c
    WHERE c.table_name = $1 AND c.table_schema = 'public'
    ORDER BY c.ordinal_position
  `, [table]);

  const cols = colsResult.rows;
  const colDefs = cols.map(col => {
    const type = buildColumnType(col);
    const nullable = col.is_nullable === 'YES' ? '' : ' NOT NULL';
    let def = '';

    if (col.is_generated === 'ALWAYS') {
      // Generated columns — recreate the expression
      def = `  "${col.column_name}" ${type} GENERATED ALWAYS AS (${col.generation_expression}) STORED`;
    } else {
      const defaultVal = col.column_default ? ` DEFAULT ${col.column_default}` : '';
      def = `  "${col.column_name}" ${type}${nullable}${defaultVal}`;
    }
    return def;
  });

  // Constraints (primary key, unique, check, foreign key)
  const constraintsResult = await client.query(`
    SELECT
      tc.constraint_name,
      tc.constraint_type,
      kcu.column_name,
      rc.update_rule,
      rc.delete_rule,
      ccu.table_name  AS foreign_table,
      ccu.column_name AS foreign_column,
      cc.check_clause
    FROM information_schema.table_constraints tc
    LEFT JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    LEFT JOIN information_schema.referential_constraints rc
      ON tc.constraint_name = rc.constraint_name
      AND tc.constraint_schema = rc.constraint_schema
    LEFT JOIN information_schema.constraint_column_usage ccu
      ON rc.unique_constraint_name = ccu.constraint_name
      AND rc.unique_constraint_schema = ccu.constraint_schema
    LEFT JOIN information_schema.check_constraints cc
      ON tc.constraint_name = cc.constraint_name
      AND tc.constraint_schema = cc.constraint_schema
    WHERE tc.table_name = $1 AND tc.table_schema = 'public'
    ORDER BY tc.constraint_type, tc.constraint_name, kcu.ordinal_position
  `, [table]);

  // Group multi-column constraints
  const constraintMap = {};
  for (const row of constraintsResult.rows) {
    if (!constraintMap[row.constraint_name]) {
      constraintMap[row.constraint_name] = { ...row, columns: [] };
    }
    if (row.column_name) {
      constraintMap[row.constraint_name].columns.push(row.column_name);
    }
  }

  const constraintDefs = [];
  for (const [name, c] of Object.entries(constraintMap)) {
    const cols_ = c.columns.map(col => `"${col}"`).join(', ');
    if (c.constraint_type === 'PRIMARY KEY') {
      constraintDefs.push(`  CONSTRAINT "${name}" PRIMARY KEY (${cols_})`);
    } else if (c.constraint_type === 'UNIQUE') {
      constraintDefs.push(`  CONSTRAINT "${name}" UNIQUE (${cols_})`);
    } else if (c.constraint_type === 'CHECK') {
      // Skip the NOT NULL checks generated by postgres internally
      if (!c.check_clause.includes('IS NOT NULL')) {
        constraintDefs.push(`  CONSTRAINT "${name}" CHECK (${c.check_clause})`);
      }
    } else if (c.constraint_type === 'FOREIGN KEY') {
      const onUpdate = c.update_rule && c.update_rule !== 'NO ACTION' ? ` ON UPDATE ${c.update_rule}` : '';
      const onDelete = c.delete_rule && c.delete_rule !== 'NO ACTION' ? ` ON DELETE ${c.delete_rule}` : '';
      constraintDefs.push(
        `  CONSTRAINT "${name}" FOREIGN KEY (${cols_}) REFERENCES "${c.foreign_table}"("${c.foreign_column}")${onUpdate}${onDelete}`
      );
    }
  }

  const allDefs = [...colDefs, ...constraintDefs];
  out += allDefs.join(',\n') + '\n';
  out += `);\n\n`;

  // Data
  const dataResult = await client.query(`SELECT * FROM "${table}"`);
  if (dataResult.rows.length > 0) {
    const columnNames = dataResult.fields
      .map(f => `"${f.name}"`)
      .join(', ');

    out += `INSERT INTO "${table}" (${columnNames}) VALUES\n`;
    dataResult.rows.forEach((row, idx) => {
      const values = dataResult.fields.map(f => escapeValue(row[f.name]));
      const comma = idx < dataResult.rows.length - 1 ? ',' : ';';
      out += `(${values.join(', ')})${comma}\n`;
    });
    out += '\n';
    log(`  → ${dataResult.rows.length} rows`);
  } else {
    log(`  → 0 rows`);
  }

  return out;
}

/**
 * Build a PostgreSQL type string from information_schema column metadata.
 */
function buildColumnType(col) {
  const dt = col.data_type.toLowerCase();

  if (dt === 'character varying') {
    return col.character_maximum_length
      ? `VARCHAR(${col.character_maximum_length})`
      : 'VARCHAR';
  }
  if (dt === 'character') {
    return col.character_maximum_length
      ? `CHAR(${col.character_maximum_length})`
      : 'CHAR';
  }
  if (dt === 'numeric' || dt === 'decimal') {
    if (col.numeric_precision && col.numeric_scale != null) {
      return `DECIMAL(${col.numeric_precision}, ${col.numeric_scale})`;
    }
    return 'DECIMAL';
  }
  if (dt === 'integer') return 'INTEGER';
  if (dt === 'bigint') return 'BIGINT';
  if (dt === 'smallint') return 'SMALLINT';
  if (dt === 'boolean') return 'BOOLEAN';
  if (dt === 'text') return 'TEXT';
  if (dt === 'json') return 'JSON';
  if (dt === 'jsonb') return 'JSONB';
  if (dt === 'date') return 'DATE';
  if (dt === 'timestamp without time zone') return 'TIMESTAMP';
  if (dt === 'timestamp with time zone') return 'TIMESTAMPTZ';
  if (dt === 'USER-DEFINED') return col.udt_name.toUpperCase(); // e.g. citext, custom enums
  // Fallback: use the raw data_type
  return col.data_type.toUpperCase();
}

// ─────────────────────────────────────────────
// INDEXES
// ─────────────────────────────────────────────

async function dumpIndexes(client) {
  const result = await client.query(`
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname NOT IN (
        -- Exclude indexes that are already defined as constraints (PK, UNIQUE)
        SELECT constraint_name
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
      )
    ORDER BY tablename, indexname
  `);

  if (result.rows.length === 0) return '';

  let out = `-- ── Indexes ─────────────────────────────────────────────────────\n\n`;
  for (const row of result.rows) {
    // Make CREATE INDEX idempotent
    const def = row.indexdef.replace(/^CREATE INDEX/, 'CREATE INDEX IF NOT EXISTS')
      .replace(/^CREATE UNIQUE INDEX/, 'CREATE UNIQUE INDEX IF NOT EXISTS');
    out += `${def};\n`;
  }
  out += '\n';
  return out;
}

// ─────────────────────────────────────────────
// SEQUENCE RESET (post-data, so IDs auto-increment correctly after restore)
// ─────────────────────────────────────────────

async function dumpSequenceResets(client, tables) {
  let out = `-- ── Sequence resets (run after data load) ───────────────────────\n\n`;

  for (const table of tables) {
    // Find serial/sequence columns for this table
    const seqResult = await client.query(`
      SELECT
        a.attname AS column_name,
        pg_get_serial_sequence($1, a.attname) AS seq_name
      FROM pg_attribute a
      JOIN pg_class c ON a.attrelid = c.oid
      JOIN pg_namespace n ON c.relnamespace = n.oid
      WHERE c.relname = $1
        AND n.nspname = 'public'
        AND a.attnum > 0
        AND NOT a.attisdropped
        AND pg_get_serial_sequence($1, a.attname) IS NOT NULL
    `, [table]);

    for (const row of seqResult.rows) {
      out += `SELECT setval('${row.seq_name}', COALESCE((SELECT MAX("${row.column_name}") FROM "${table}"), 1));\n`;
    }
  }

  out += '\n';
  return out;
}

// ─────────────────────────────────────────────
// COMPRESS + EMAIL
// ─────────────────────────────────────────────

async function dumpAndSendBackup() {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) throw new Error('DATABASE_URL is not set in .env.local');

  const dbNameMatch = dbUrl.match(/\/([^/?]+)(\?|$)/);
  const dbname = dbNameMatch ? dbNameMatch[1] : 'database';
  const filename = `${dbname}_${getTimestamp()}.sql.gz`;

  log(`Starting full backup of "${dbname}"...`);

  const sqlDump = await dumpDatabase();
  const rawMB = (Buffer.byteLength(sqlDump, 'utf8') / 1024 / 1024).toFixed(2);
  log(`Dump complete → ${rawMB} MB uncompressed`);

  // Verify the dump is not suspiciously small
  if (Buffer.byteLength(sqlDump, 'utf8') < 500) {
    throw new Error('Dump appears too small — possible empty/failed dump. Aborting.');
  }

  const compressed = await new Promise((resolve, reject) => {
    const gzip = createGzip({ level: 9 });
    const chunks = [];
    gzip.on('data', chunk => chunks.push(chunk));
    gzip.on('end', () => resolve(Buffer.concat(chunks)));
    gzip.on('error', reject);
    gzip.write(sqlDump);
    gzip.end();
  });

  const compMB = (compressed.length / 1024 / 1024).toFixed(2);
  log(`Compressed → ${compMB} MB`);

  await sendBackupEmail(compressed, filename, rawMB, compMB);
  return { filename, size: compMB };
}

// ─────────────────────────────────────────────
// EMAIL
// ─────────────────────────────────────────────

async function sendBackupEmail(buffer, filename, rawMB, compMB) {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_APP_PASSWORD) {
    log('Email credentials not set — backup completed but not emailed.');
    return;
  }

  log(`Emailing backup to ${process.env.EMAIL_USER}...`);

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_APP_PASSWORD,
    },
  });

  await transporter.sendMail({
    from: `"Sabino Backup" <${process.env.EMAIL_USER}>`,
    to: process.env.EMAIL_USER,
    subject: `🗄️ DB Backup: ${filename}`,
    html: `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 500px;">
        <h2 style="color: #2c3e50;">✅ Database Backup Complete</h2>
        <table style="border-collapse: collapse; width: 100%;">
          <tr><td style="padding: 6px; color: #666;">Timestamp</td><td><strong>${new Date().toLocaleString()}</strong></td></tr>
          <tr><td style="padding: 6px; color: #666;">Filename</td><td><strong>${filename}</strong></td></tr>
          <tr><td style="padding: 6px; color: #666;">Raw size</td><td><strong>${rawMB} MB</strong></td></tr>
          <tr><td style="padding: 6px; color: #666;">Compressed</td><td><strong>${compMB} MB</strong></td></tr>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #999;">
          Automated backup from Sabino Edu. To restore: <code>gunzip -c ${filename} | psql &lt;DATABASE_URL&gt;</code>
        </p>
      </div>
    `,
    attachments: [
      {
        filename,
        content: buffer,
        contentType: 'application/gzip',
      },
    ],
  });

  log('✅ Email sent successfully');
}

// ─────────────────────────────────────────────
// ENTRY POINT
// ─────────────────────────────────────────────

async function runBackup() {
  log('Starting backup task...');
  try {
    const { filename, size } = await dumpAndSendBackup();
    log(`✅ Backup finished: ${filename} (${size} MB compressed)`);
  } catch (err) {
    log(`❌ Backup FAILED: ${err.message}`);
    // Do not rethrow — cron runner handles graceful degradation
  }
}

module.exports = { runBackup };

// Direct execution: node backup-db.js
if (require.main === module) {
  runBackup()
    .then(() => process.exit(0))
    .catch(err => { console.error(err); process.exit(1); });
}